required = [
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    ]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.5"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/openshift/cluster-api"
  branch = "openshift-4.0-cluster-api-0.0.0-alpha.4"

[[override]]
  name = "github.com/openshift/cluster-api-actuator-pkg"
  branch = "master"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
 [[override]]
   name = "gopkg.in/fsnotify.v1"
   source = "https://github.com/fsnotify/fsnotify.git"
   version="v1.4.7"

[prune]
  go-tests = true

  [[prune.project]]
    name = "github.com/openshift/cluster-api-actuator-pkg"
    go-tests = false
